; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\ai_script_lua_debug.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BN@JJDDBCCB@cannot?5resume?5dead?5coroutine?$AA@ ; `string'
PUBLIC	??_C@_0BG@HEJOLIAF@Script?5?$CFs?5is?5finished?$AA@ ; `string'
PUBLIC	??_C@_0P@BLGHDAIL@Output?5from?5?$CFs?$AA@	; `string'
PUBLIC	??_C@_0BH@NLJICJPP@?$CB?5SCRIPT?5RUNTIME?5ERROR?$AA@ ; `string'
PUBLIC	??_C@_0CD@GJICNBMP@?$CB?5SCRIPT?5ERROR?5?$CImemory?5allocatio@ ; `string'
PUBLIC	??_C@_0DK@JDJAKDKL@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5th@ ; `string'
PUBLIC	??_C@_0CE@DCLMKMEA@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5fi@ ; `string'
PUBLIC	??_C@_0BG@EJHPPKKH@?$CB?5SCRIPT?5SYNTAX?5ERROR?$AA@ ; `string'
PUBLIC	??_C@_0BB@GCDGCJFB@?$CB?5Stack?5level?5?$CFd?$AA@ ; `string'
PUBLIC	??_C@_09PMELJFC@hook?5call?$AA@			; `string'
PUBLIC	??_C@_0M@LBICNABH@hook?5return?$AA@		; `string'
PUBLIC	??_C@_09JKGGGJEL@hook?5line?$AA@		; `string'
PUBLIC	??_C@_0L@FPJMDKIJ@hook?5count?$AA@		; `string'
PUBLIC	??_C@_0BB@HFNAPKFC@hook?5tail?5return?$AA@	; `string'
EXTRN	__imp__lua_isstring:PROC
EXTRN	__imp__lua_tolstring:PROC
;	COMDAT ??_C@_0BB@HFNAPKFC@hook?5tail?5return?$AA@
CONST	SEGMENT
??_C@_0BB@HFNAPKFC@hook?5tail?5return?$AA@ DB 'hook tail return', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@FPJMDKIJ@hook?5count?$AA@
CONST	SEGMENT
??_C@_0L@FPJMDKIJ@hook?5count?$AA@ DB 'hook count', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09JKGGGJEL@hook?5line?$AA@
CONST	SEGMENT
??_C@_09JKGGGJEL@hook?5line?$AA@ DB 'hook line', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@LBICNABH@hook?5return?$AA@
CONST	SEGMENT
??_C@_0M@LBICNABH@hook?5return?$AA@ DB 'hook return', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_09PMELJFC@hook?5call?$AA@
CONST	SEGMENT
??_C@_09PMELJFC@hook?5call?$AA@ DB 'hook call', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@GCDGCJFB@?$CB?5Stack?5level?5?$CFd?$AA@
CONST	SEGMENT
??_C@_0BB@GCDGCJFB@?$CB?5Stack?5level?5?$CFd?$AA@ DB '! Stack level %d', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@EJHPPKKH@?$CB?5SCRIPT?5SYNTAX?5ERROR?$AA@
CONST	SEGMENT
??_C@_0BG@EJHPPKKH@?$CB?5SCRIPT?5SYNTAX?5ERROR?$AA@ DB '! SCRIPT SYNTAX E'
	DB	'RROR', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0CE@DCLMKMEA@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5fi@
CONST	SEGMENT
??_C@_0CE@DCLMKMEA@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5fi@ DB '! SCR'
	DB	'IPT ERROR (while running file)', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DK@JDJAKDKL@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5th@
CONST	SEGMENT
??_C@_0DK@JDJAKDKL@?$CB?5SCRIPT?5ERROR?5?$CIwhile?5running?5th@ DB '! SCR'
	DB	'IPT ERROR (while running the error handler function)', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CD@GJICNBMP@?$CB?5SCRIPT?5ERROR?5?$CImemory?5allocatio@
CONST	SEGMENT
??_C@_0CD@GJICNBMP@?$CB?5SCRIPT?5ERROR?5?$CImemory?5allocatio@ DB '! SCRI'
	DB	'PT ERROR (memory allocation)', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@NLJICJPP@?$CB?5SCRIPT?5RUNTIME?5ERROR?$AA@
CONST	SEGMENT
??_C@_0BH@NLJICJPP@?$CB?5SCRIPT?5RUNTIME?5ERROR?$AA@ DB '! SCRIPT RUNTIME'
	DB	' ERROR', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@BLGHDAIL@Output?5from?5?$CFs?$AA@
CONST	SEGMENT
??_C@_0P@BLGHDAIL@Output?5from?5?$CFs?$AA@ DB 'Output from %s', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@HEJOLIAF@Script?5?$CFs?5is?5finished?$AA@
CONST	SEGMENT
??_C@_0BG@HEJOLIAF@Script?5?$CFs?5is?5finished?$AA@ DB 'Script %s is fini'
	DB	'shed', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@JJDDBCCB@cannot?5resume?5dead?5coroutine?$AA@
CONST	SEGMENT
??_C@_0BN@JJDDBCCB@cannot?5resume?5dead?5coroutine?$AA@ DB 'cannot resume'
	DB	' dead coroutine', 00H			; `string'
END
