; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\Device_overdraw.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?overdrawEnd@CRenderDevice@@QAEXXZ		; CRenderDevice::overdrawEnd
; Function compile flags: /Ogtpy
; File d:\clearsky\sources\engine\xrengine\device_overdraw.cpp
;	COMDAT ?overdrawEnd@CRenderDevice@@QAEXXZ
_TEXT	SEGMENT
?overdrawEnd@CRenderDevice@@QAEXXZ PROC			; CRenderDevice::overdrawEnd, COMDAT
; _this$ = ecx

; 11   : 	VERIFY(0);
; 12   : 	m_pRender->overdrawEnd();

	mov	ecx, DWORD PTR [ecx+868]
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax+60]
	jmp	edx
?overdrawEnd@CRenderDevice@@QAEXXZ ENDP			; CRenderDevice::overdrawEnd
_TEXT	ENDS
PUBLIC	?overdrawBegin@CRenderDevice@@QAEXXZ		; CRenderDevice::overdrawBegin
; Function compile flags: /Ogtpy
;	COMDAT ?overdrawBegin@CRenderDevice@@QAEXXZ
_TEXT	SEGMENT
?overdrawBegin@CRenderDevice@@QAEXXZ PROC		; CRenderDevice::overdrawBegin, COMDAT
; _this$ = ecx

; 5    : 	VERIFY(0);
; 6    : 	m_pRender->overdrawBegin();

	mov	ecx, DWORD PTR [ecx+868]
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax+56]
	jmp	edx
?overdrawBegin@CRenderDevice@@QAEXXZ ENDP		; CRenderDevice::overdrawBegin
END
