; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\doug_lea_memory_allocator.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BK@NOJBAIDO@max?5system?5bytes?5?$DN?5?$CF10lu?6?$AA@ ; `string'
PUBLIC	??_C@_0BK@HGDMIJJL@system?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@ ; `string'
PUBLIC	??_C@_0BK@GOGELADF@in?5use?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@ ; `string'
EXTRN	__imp__VirtualAlloc@16:PROC
EXTRN	__imp__VirtualFree@12:PROC
;	COMDAT ??_C@_0BK@GOGELADF@in?5use?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@
CONST	SEGMENT
??_C@_0BK@GOGELADF@in?5use?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@ DB 'in u'
	DB	'se bytes     = %10lu', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@HGDMIJJL@system?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@
CONST	SEGMENT
??_C@_0BK@HGDMIJJL@system?5bytes?5?5?5?5?5?$DN?5?$CF10lu?6?$AA@ DB 'syste'
	DB	'm bytes     = %10lu', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@NOJBAIDO@max?5system?5bytes?5?$DN?5?$CF10lu?6?$AA@
CONST	SEGMENT
??_C@_0BK@NOJBAIDO@max?5system?5bytes?5?$DN?5?$CF10lu?6?$AA@ DB 'max syst'
	DB	'em bytes = %10lu', 0aH, 00H			; `string'
END
