; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\IGame_Level_check_textures.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BM@PKKHPKLL@?$CK?5t?9report?5?9?5base?3?5?$CFd?0?5?$CFd?5K?$AA@ ; `string'
PUBLIC	??_C@_0BM@HNMBPKJO@?$CK?5t?9report?5?9?5lmap?3?5?$CFd?0?5?$CFd?5K?$AA@ ; `string'
;	COMDAT ??_C@_0BM@HNMBPKJO@?$CK?5t?9report?5?9?5lmap?3?5?$CFd?0?5?$CFd?5K?$AA@
CONST	SEGMENT
??_C@_0BM@HNMBPKJO@?$CK?5t?9report?5?9?5lmap?3?5?$CFd?0?5?$CFd?5K?$AA@ DB '*'
	DB	' t-report - lmap: %d, %d K', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@PKKHPKLL@?$CK?5t?9report?5?9?5base?3?5?$CFd?0?5?$CFd?5K?$AA@
CONST	SEGMENT
??_C@_0BM@PKKHPKLL@?$CK?5t?9report?5?9?5base?3?5?$CFd?0?5?$CFd?5K?$AA@ DB '*'
	DB	' t-report - base: %d, %d K', 00H		; `string'
PUBLIC	?LL_CheckTextures@IGame_Level@@QAEXXZ		; IGame_Level::LL_CheckTextures
; Function compile flags: /Ogtpy
; File d:\clearsky\sources\engine\xrengine\igame_level_check_textures.cpp
;	COMDAT ?LL_CheckTextures@IGame_Level@@QAEXXZ
_TEXT	SEGMENT
_m_base$ = -16						; size = 4
_c_base$ = -12						; size = 4
_m_lmaps$ = -8						; size = 4
_c_lmaps$ = -4						; size = 4
?LL_CheckTextures@IGame_Level@@QAEXXZ PROC		; IGame_Level::LL_CheckTextures, COMDAT
; _this$ = ecx

; 7    : 	u32	m_base,c_base,m_lmaps,c_lmaps;
; 8    : 	//Device.Resources->_GetMemoryUsage		(m_base,c_base,m_lmaps,c_lmaps);
; 9    : 	Device.m_pRender->ResourcesGetMemoryUsage(m_base,c_base,m_lmaps,c_lmaps);

	mov	ecx, DWORD PTR ?Device@@3VCRenderDevice@@A+868
	mov	eax, DWORD PTR [ecx]
	mov	eax, DWORD PTR [eax+72]
	sub	esp, 16					; 00000010H
	push	esi
	lea	edx, DWORD PTR _c_lmaps$[esp+20]
	push	edx
	lea	edx, DWORD PTR _m_lmaps$[esp+24]
	push	edx
	lea	edx, DWORD PTR _c_base$[esp+28]
	push	edx
	lea	edx, DWORD PTR _m_base$[esp+32]
	push	edx
	call	eax

; 10   : 
; 11   : 	Msg	("* t-report - base: %d, %d K",	c_base,		m_base/1024);

	mov	ecx, DWORD PTR _m_base$[esp+20]
	mov	edx, DWORD PTR _c_base$[esp+20]
	mov	esi, DWORD PTR __imp_?Msg@@YAXPBDZZ
	shr	ecx, 10					; 0000000aH
	push	ecx
	push	edx
	push	OFFSET ??_C@_0BM@PKKHPKLL@?$CK?5t?9report?5?9?5base?3?5?$CFd?0?5?$CFd?5K?$AA@
	call	esi

; 12   : 	Msg	("* t-report - lmap: %d, %d K",	c_lmaps,	m_lmaps/1024);

	mov	eax, DWORD PTR _m_lmaps$[esp+32]
	mov	ecx, DWORD PTR _c_lmaps$[esp+32]
	shr	eax, 10					; 0000000aH
	push	eax
	push	ecx
	push	OFFSET ??_C@_0BM@HNMBPKJO@?$CK?5t?9report?5?9?5lmap?3?5?$CFd?0?5?$CFd?5K?$AA@
	call	esi
	add	esp, 24					; 00000018H
	pop	esi

; 13   : 	BOOL	bError	= FALSE;
; 14   : 	if (m_base>64*1024*1024 || c_base>400)
; 15   : 	{
; 16   : 		// LPCSTR msg	= "Too many base-textures (limit: 400 textures or 64M).\n        Reduce number of textures (better) or their resolution (worse).";
; 17   : 		// Msg		("***FATAL***: %s",msg);
; 18   : 		bError		= TRUE;
; 19   : 	}
; 20   : 	if (m_lmaps>32*1024*1024 || c_lmaps>8)
; 21   : 	{
; 22   : #ifdef DEBUG
; 23   : 		LPCSTR msg	= "Too many lmap-textures (limit: 8 textures or 32M).\n        Reduce pixel density (worse) or use more vertex lighting (better).";
; 24   : 		Msg			("***FATAL***: %s",msg);
; 25   : #endif // #ifdef DEBUG
; 26   : 		bError		= TRUE;
; 27   : 	}
; 28   : }

	add	esp, 16					; 00000010H
	ret	0
?LL_CheckTextures@IGame_Level@@QAEXXZ ENDP		; IGame_Level::LL_CheckTextures
END
