; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\phdebug.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?ph_debug_render@@3PAUIPhDebugRender@@A		; ph_debug_render
?ph_debug_render@@3PAUIPhDebugRender@@A DD 01H DUP (?)	; ph_debug_render
END
