; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.762 

	TITLE	D:\CLEARSKY\sources\engine\xrEngine\pure.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?rp_ScreenResolutionChanged@@YIXPAX@Z		; rp_ScreenResolutionChanged
; Function compile flags: /Ogtpy
; File d:\clearsky\sources\engine\xrengine\pure.cpp
;	COMDAT ?rp_ScreenResolutionChanged@@YIXPAX@Z
_TEXT	SEGMENT
?rp_ScreenResolutionChanged@@YIXPAX@Z PROC		; rp_ScreenResolutionChanged, COMDAT
; _p$ = ecx

; 20   : DECLARE_RP(ScreenResolutionChanged);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_ScreenResolutionChanged@@YIXPAX@Z ENDP		; rp_ScreenResolutionChanged
_TEXT	ENDS
PUBLIC	?rp_DeviceReset@@YIXPAX@Z			; rp_DeviceReset
; Function compile flags: /Ogtpy
;	COMDAT ?rp_DeviceReset@@YIXPAX@Z
_TEXT	SEGMENT
?rp_DeviceReset@@YIXPAX@Z PROC				; rp_DeviceReset, COMDAT
; _p$ = ecx

; 19   : DECLARE_RP(DeviceReset);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_DeviceReset@@YIXPAX@Z ENDP				; rp_DeviceReset
_TEXT	ENDS
PUBLIC	?rp_AppEnd@@YIXPAX@Z				; rp_AppEnd
; Function compile flags: /Ogtpy
;	COMDAT ?rp_AppEnd@@YIXPAX@Z
_TEXT	SEGMENT
?rp_AppEnd@@YIXPAX@Z PROC				; rp_AppEnd, COMDAT
; _p$ = ecx

; 18   : DECLARE_RP(AppEnd);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_AppEnd@@YIXPAX@Z ENDP				; rp_AppEnd
_TEXT	ENDS
PUBLIC	?rp_AppStart@@YIXPAX@Z				; rp_AppStart
; Function compile flags: /Ogtpy
;	COMDAT ?rp_AppStart@@YIXPAX@Z
_TEXT	SEGMENT
?rp_AppStart@@YIXPAX@Z PROC				; rp_AppStart, COMDAT
; _p$ = ecx

; 17   : DECLARE_RP(AppStart);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_AppStart@@YIXPAX@Z ENDP				; rp_AppStart
_TEXT	ENDS
PUBLIC	?rp_AppDeactivate@@YIXPAX@Z			; rp_AppDeactivate
; Function compile flags: /Ogtpy
;	COMDAT ?rp_AppDeactivate@@YIXPAX@Z
_TEXT	SEGMENT
?rp_AppDeactivate@@YIXPAX@Z PROC			; rp_AppDeactivate, COMDAT
; _p$ = ecx

; 16   : DECLARE_RP(AppDeactivate);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_AppDeactivate@@YIXPAX@Z ENDP			; rp_AppDeactivate
_TEXT	ENDS
PUBLIC	?rp_AppActivate@@YIXPAX@Z			; rp_AppActivate
; Function compile flags: /Ogtpy
;	COMDAT ?rp_AppActivate@@YIXPAX@Z
_TEXT	SEGMENT
?rp_AppActivate@@YIXPAX@Z PROC				; rp_AppActivate, COMDAT
; _p$ = ecx

; 15   : DECLARE_RP(AppActivate);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_AppActivate@@YIXPAX@Z ENDP				; rp_AppActivate
_TEXT	ENDS
PUBLIC	?rp_Render@@YIXPAX@Z				; rp_Render
; Function compile flags: /Ogtpy
;	COMDAT ?rp_Render@@YIXPAX@Z
_TEXT	SEGMENT
?rp_Render@@YIXPAX@Z PROC				; rp_Render, COMDAT
; _p$ = ecx

; 14   : DECLARE_RP(Render);

	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	jmp	edx
?rp_Render@@YIXPAX@Z ENDP				; rp_Render
_TEXT	ENDS
PUBLIC	?rp_Frame@@YIXPAX@Z				; rp_Frame
; Function compile flags: /Ogtpy
;	COMDAT ?rp_Frame@@YIXPAX@Z
_TEXT	SEGMENT
?rp_Frame@@YIXPAX@Z PROC				; rp_Frame, COMDAT
; _p$ = ecx

; 13   : DECLARE_RP(Frame);

	mov	eax, DWORD PTR [ecx]
	push	ecx
	mov	ecx, DWORD PTR [eax]
	call	ecx
	ret	0
?rp_Frame@@YIXPAX@Z ENDP				; rp_Frame
END
